#---------------------------------#
#  Interface for the generators  
#  This interface is used to define the contract for the generators.
#  It is used to ensure that the generators are consistent and can be used interchangeably.
#  It is also used to define the methods that the generators must implement.
#---------------------------------#

from abc import ABC, abstractmethod
from enum import Enum
from typing import List, Dict, Any

from dataclasses import dataclass

@dataclass
class ChatRole(Enum):
    """
        Chat role enum to represent the role of the message. Most of the time, chat-based LLMs use the following roles:
        - USER: that represents the message that the user has sent to the LLM.
        - ASSISTANT: that represents the answer that the LLM has sent to the user.
        - SYSTEM: that represents the instructions that the LLM has to follow (provided by the user).
    """
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


@dataclass
class ChatMessage:
    """
        Chat message to represent a message that has been sent to the LLM. It contains the role of the message and the content of the message.
        Args:
            role: The role of the message.
            content: The content of the message.
        Returns:
            dict: The dictionary representation of the chat message.
    """
    role: ChatRole
    content: str

    def to_dict(self) -> dict:
        """
        Convert the chat message to a dictionary.
        """
        return {
            "role": self.role.value,
            "content": self.content,
        }


class Generator(ABC):
    """
        Abstract base class for generators. Generators are responsible for generating completions from a prompt.
        Args:
            model: The model to use for the generator.
            tokenizer: The tokenizer to use for the generator.
            config: The configuration to use for the generator.
        Returns:
            Generator: The generator instance.
    """
    model: Any
    tokenizer: Any
    config: Dict[str, Any]

    """
    Abstract base class for generators.
    """
    @abstractmethod
    def generate(self, prompt: str) -> str:
        """
            Generate a completion from the generator.
            Args:
                prompt: The prompt to generate a completion from.
            Returns:
                str: The completion generated by the generator.
        """
        raise NotImplementedError

    def batch_generate(self, prompts: List[str]) -> List[str]:
        """
            Generate completions for multiple prompts in one batched forward pass.
            Args:
                prompts: The prompts to generate completions from.
            Returns:
                List[str]: The completions generated by the generator.
        """
        raise NotImplementedError

    @abstractmethod
    def chat_generation(self, messages: List[ChatMessage]) -> str:
        """
            Generate a completion from the generator.
        """
        raise NotImplementedError

    def batch_chat_generation(self, messages: List[List[ChatMessage]]) -> List[str]:
        """
            Generate completions for multiple chat messages in one batched forward pass.
            Args:
                messages: The chat messages to generate completions from.
            Returns:
                List[str]: The completions generated by the generator.
        """
        raise NotImplementedError
